export const provinces = [
    { name: 'Aceh', code: 'Aceh' },
    { name: 'Bali', code: 'Bali' },
    { name: 'Bangka Belitung', code: 'Bangka Belitung' },
    { name: 'Banten', code: 'Banten' },
    { name: 'Bengkulu', code: 'Bengkulu' },
    { name: 'Gorontalo', code: 'Gorontalo' },
    { name: 'Jakarta', code: 'Jakarta' },
    { name: 'Jambi', code: 'Jambi' },
    { name: 'Jawa Barat', code: 'Jawa Barat' },
    { name: 'Jawa Tengah', code: 'Jawa Tengah' },
    { name: 'Jawa Timur', code: 'Jawa Timur' },
    { name: 'Kalimantan Barat', code: 'Kalimantan Barat' },
    { name: 'Kalimantan Selatan', code: 'Kalimantan Selatan' },
    { name: 'Kalimantan Tengah', code: 'Kalimantan Tengah' },
    { name: 'Kalimantan Timur', code: 'Kalimantan Timur' },
    { name: 'Kalimantan Utara', code: 'Kalimantan Utara' },
    { name: 'Kepulauan Riau', code: 'Kepulauan Riau' },
    { name: 'Lampung', code: 'Lampung' },
    { name: 'Maluku', code: 'Maluku' },
    { name: 'Maluku Utara', code: 'Maluku Utara' },
    { name: 'Nusa Tenggara Barat', code: 'Nusa Tenggara Barat' },
    { name: 'Nusa Tenggara Timur', code: 'Nusa Tenggara Timur' },
    { name: 'Papua', code: 'Papua' },
    { name: 'Papua Barat', code: 'Papua Barat' },
    { name: 'Riau', code: 'Riau' },
    { name: 'Sulawesi Barat', code: 'Sulawesi Barat' },
    { name: 'Sulawesi Selatan', code: 'Sulawesi Selatan' },
    { name: 'Sulawesi Tengah', code: 'Sulawesi Tengah' },
    { name: 'Sulawesi Tenggara', code: 'Sulawesi Tenggara' },
    { name: 'Sulawesi Utara', code: 'Sulawesi Utara' },
    { name: 'Sumatera Barat', code: 'Sumatera Barat' },
    { name: 'Sumatera Selatan', code: 'Sumatera Selatan' },
    { name: 'Sumatera Utara', code: 'Sumatera Utara' }
  ];

 export const types = [
    {name : 'CONTRACTOR', code: 'CONTRACTOR'},
    {name : 'PLANTATION', code: 'PLANTATION'},
    {name : 'OTHERS', code: 'OTHERS'}
  ]